name: default
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - anyio=4.11.0
  - aom=3.9.1
  - asttokens=2.4.1
  - av=13.1.0
  - backports=1.0
  - backports.tarfile=1.2.0
  - blas=1.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - cachecontrol=0.14.3
  - cachecontrol-with-filecache=0.14.3
  - cairo=1.18.4
  - cffi=1.17.1
  - cleo=2.1.0
  - cloup=3.0.8
  - colorama=0.4.6
  - comm=0.2.1
  - crashtest=0.4.1
  - cryptography=46.0.3
  - dav1d=1.2.1
  - dbus=1.13.6
  - debugpy=1.6.7
  - decorator=5.1.1
  - distlib=0.4.0
  - dulwich=0.24.10
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - expat=2.7.1
  - ffmpeg=7.1.0
  - findpython=0.6.3
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.13.3
  - fribidi=1.0.16
  - giflib=5.2.2
  - glcontext=3.0.0
  - glib=2.84.4
  - glib-tools=2.84.4
  - gmp=6.3.0
  - graphite2=1.3.14
  - h2=4.3.0
  - harfbuzz=10.4.0
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=75.1
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - importlib_resources=6.5.2
  - intel-openmp=2025.0.0
  - ipykernel=6.28.0
  - ipython=8.19.0
  - isosurfaces=0.1.2
  - jaraco.classes=3.4.0
  - jaraco.context=6.0.1
  - jaraco.functools=4.3.0
  - jedi=0.19.1
  - jeepney=0.9.0
  - jpeg=9e
  - jupyter_client=8.6.0
  - jupyter_core=5.7.0
  - keyring=25.7.0
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.38
  - leptonica=1.82.0
  - lerc=4.0.0
  - libabseil=20240722.0
  - libarchive=3.8.2
  - libass=0.17.3
  - libavif=1.1.1
  - libavif16=1.1.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libdeflate=1.22
  - libdrm=2.4.125
  - libegl=1.7.0
  - libexpat=2.7.1
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgd=2.3.3
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libgl=1.7.0
  - libglib=2.84.4
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.2.0
  - libhwloc=2.12.1
  - libiconv=1.18
  - liblapack=3.9.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnsl=2.0.1
  - libogg=1.3.5
  - libopenjpeg=2.5.4
  - libopenvino=2024.4.0
  - libopenvino-auto-batch-plugin=2024.4.0
  - libopenvino-auto-plugin=2024.4.0
  - libopenvino-hetero-plugin=2024.4.0
  - libopenvino-intel-cpu-plugin=2024.4.0
  - libopenvino-intel-gpu-plugin=2024.4.0
  - libopenvino-intel-npu-plugin=2024.4.0
  - libopenvino-ir-frontend=2024.4.0
  - libopenvino-onnx-frontend=2024.4.0
  - libopenvino-paddle-frontend=2024.4.0
  - libopenvino-pytorch-frontend=2024.4.0
  - libopenvino-tensorflow-frontend=2024.4.0
  - libopenvino-tensorflow-lite-frontend=2024.4.0
  - libopus=1.5.2
  - libpciaccess=0.18
  - libpng=1.6.50
  - libprotobuf=5.28.2
  - libsodium=1.0.18
  - libsqlite=3.51.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libta-lib=0.6.4
  - libtheora=1.2.0
  - libtiff=4.7.0
  - libuuid=2.41.2
  - libva=2.22.0
  - libvorbis=1.3.7
  - libvpx=1.14.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxml2=2.13.9
  - libzlib=1.3.1
  - llvm-openmp=20.1.8
  - lz4-c=1.9.4
  - manim=0.19.0
  - manimpango=0.6.0
  - mapbox_earcut=1.0.3
  - matplotlib-inline=0.1.6
  - mdurl=0.1.2
  - mkl=2024.2.2
  - mkl-service=2.5.2
  - mkl_fft=2.0.0
  - mkl_random=1.2.11
  - moderngl=5.11.1
  - moderngl-window=3.1.1
  - more-itertools=10.8.0
  - msgpack-python=1.1.2
  - ncurses=6.5
  - nest-asyncio=1.5.8
  - networkx=3.4.2
  - ocl-icd=2.3.3
  - opencl-headers=2025.06.13
  - openh264=2.4.1
  - openjpeg=2.5.4
  - openssl=3.6.0
  - pandas-ta=0.3.14b
  - pango=1.54.0
  - parso=0.8.3
  - pbs-installer=2025.10.31
  - pcre2=10.46
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pixman=0.46.4
  - pkginfo=1.12.1.2
  - platformdirs=4.1.0
  - poetry=2.2.1
  - poetry-core=2.2.1
  - prompt-toolkit=3.0.42
  - psutil=5.9.7
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pugixml=1.14
  - pure_eval=0.2.2
  - pycairo=1.27.0
  - pycparser=2.22
  - pydub=0.25.1
  - pyglet=2.1.11
  - pyglm=2.8.2
  - pygments=2.17.2
  - pyproject_hooks=1.2.0
  - pysocks=1.7.1
  - python=3.10.19
  - python-build=1.3.0
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.2
  - python-installer=0.7.0
  - python-tzdata=2025.2
  - python_abi=3.10
  - pyzmq=25.1.0
  - rapidfuzz=3.14.3
  - rav1e=0.6.6
  - readline=8.2
  - requests-toolbelt=1.0.0
  - scipy=1.15.2
  - screeninfo=0.8.1
  - secretstorage=3.4.1
  - setuptools=68.2.2
  - shellingham=1.5.4
  - six=1.17.0
  - skia-pathops=0.9.0
  - snappy=1.2.2
  - sniffio=1.3.1
  - sqlite=3.51.0
  - srt=3.5.3
  - stack_data=0.6.2
  - svgelements=1.9.6
  - svt-av1=2.2.1
  - ta-lib=0.6.4
  - tbb=2021.13.0
  - tesseract=5.2.0
  - tk=8.6.13
  - tornado=6.3.3
  - tqdm=4.67.1
  - traitlets=5.14.1
  - trove-classifiers=2025.11.14.15
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - virtualenv=20.35.4
  - watchdog=6.0.0
  - wayland=1.23.1
  - wayland-protocols=1.45
  - wcwidth=0.2.12
  - wheel=0.41.2
  - x264=1!164.3095
  - x265=3.5
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.2
  - xorg-libxrender=0.9.12
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.17.0
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - absl-py==2.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.14
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - astroid==3.3.9
      - astunparse==1.6.3
      - async-timeout==5.0.1
      - attrs==23.2.0
      - beautifulsoup4==4.13.3
      - bidict==0.23.1
      - blinker==1.9.0
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - click==8.1.8
      - colorcet==3.1.0
      - contourpy==1.3.1
      - cycler==0.12.1
      - dateparser==1.2.2
      - dicttoxml==1.7.16
      - dill==0.4.0
      - distro==1.9.0
      - fastjsonschema==2.19.1
      - filelock==3.17.0
      - flask==3.1.0
      - flask-socketio==5.5.1
      - flatbuffers==25.2.10
      - fonttools==4.56.0
      - frozenlist==1.5.0
      - fsspec==2025.3.0
      - gast==0.6.0
      - gdown==5.2.0
      - google-pasta==0.2.0
      - grpcio==1.71.0
      - gurobipy==11.0.3
      - h11==0.14.0
      - h5py==3.13.0
      - idna==3.10
      - imageio==2.37.0
      - ipywidgets==8.1.5
      - isodate==0.7.2
      - isort==6.0.1
      - itsdangerous==2.2.0
      - jax==0.4.25
      - jaxlib==0.4.25+cuda11.cudnn86
      - jinja2==3.1.6
      - jiter==0.11.0
      - joblib==1.4.2
      - jsonpickle==3.3.0
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - jupyterlab-widgets==3.0.13
      - kaggle==1.7.4.5
      - kagglehub==0.3.13
      - keras==3.8.0
      - kiwisolver==1.4.8
      - liac-arff==2.5.0
      - libclang==18.1.1
      - lightning-utilities==0.14.2
      - llvmlite==0.39.1
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.1
      - mccabe==0.7.0
      - minio==7.2.15
      - ml-dtypes==0.4.1
      - mpmath==1.3.0
      - multidict==6.2.0
      - mypy-extensions==1.1.0
      - namex==0.0.8
      - nbformat==5.9.2
      - netron==8.2.0
      - numba==0.56.4
      - numpy==1.23.5
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.1.105
      - onnx==1.17.0
      - openai==2.3.0
      - openml==0.15.1
      - openml-pytorch==0.1.5
      - opt-einsum==3.3.0
      - optree==0.14.0
      - outcome==1.3.0.post0
      - packaging==23.1
      - pandas==2.2.3
      - pillow==11.1.0
      - pip==24.0
      - plotly==5.18.0
      - powerlaw==1.5
      - propcache==0.3.0
      - protobuf==6.30.0
      - pyarrow==19.0.1
      - pycryptodome==3.21.0
      - pydantic==2.12.0
      - pydantic-core==2.41.1
      - pygame==2.6.1
      - pygraphviz==1.14
      - pylint==3.3.6
      - pyparsing==3.2.1
      - python-binance==1.0.29
      - python-dotenv==1.1.1
      - python-engineio==4.12.0
      - python-graphviz==0.20.3
      - python-slugify==8.0.4
      - python-socketio==5.13.0
      - pytorch-lightning==2.2.1
      - pytz==2025.1
      - pyvis==0.3.2
      - pyyaml==6.0.2
      - rdflib==7.1.1
      - referencing==0.33.0
      - regex==2025.9.18
      - requests==2.32.3
      - rich==13.9.4
      - rpds-py==0.18.0
      - schedule==1.2.2
      - scikit-learn==1.6.1
      - seaborn==0.13.1
      - selenium==4.31.0
      - simple-websocket==1.1.0
      - sortedcontainers==2.4.0
      - soupsieve==2.6
      - speechrecognition==3.14.1
      - sympy==1.13.1
      - tenacity==8.2.3
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.18.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==2.5.0
      - text-unidecode==1.3
      - threadpoolctl==3.5.0
      - tomli==2.2.1
      - tomlkit==0.13.2
      - torch==2.2.0+cu121
      - torchaudio==2.2.0+cu121
      - torchmetrics==1.7.0
      - torchvision==0.17.0+cu121
      - trio==0.30.0
      - trio-websocket==0.12.2
      - triton==2.2.0
      - typing-inspection==0.4.2
      - tzdata==2025.1
      - tzlocal==5.3.1
      - urllib3==2.3.0
      - vectorbt==0.28.1
      - websocket-client==1.8.0
      - websockets==15.0.1
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.13
      - wrapt==1.17.2
      - wsproto==1.2.0
      - xgboost==3.0.0
      - xmltodict==0.14.2
      - yarl==1.18.3
